# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Daniel Iwugo <ops@themalwarefiles.com>
# Author:  Daniel Iwugo
# Comment: Christ is King  # noqa: ERA001
"""The social cards are the size their filename claims, and carry the identity they claim.

WHY THIS EXISTS

The Bloom kit has been replaced once, in `b02383a`, and that commit message records what the
previous check missed: "the file is present" was exactly the test that did not catch a set of
broken exports. The assets it replaced were mostly empty space with a downsampled mark.

So this reads the pixels. Each card has to be the platform's own stated size, has to be small enough
for the surface that will accept it, and has to look like the kit: the background is the kit's navy,
the ink is the kit's pink through purple, and neither the mark nor the wordmark has gone missing.

A card is generated by `tools/packaging/build_brand_assets.py` from `assets/brand/mark.svg` and the
wordmark on `docs/public/social-card.png`, so if one of those moves this fails rather than the kit
quietly drifting into two identities.
"""
from __future__ import annotations

import pathlib
import struct

import pytest

ROOT = pathlib.Path(__file__).resolve().parents[1]
SOCIAL = ROOT / "assets" / "brand" / "social"

#: The kit's background, the last stop of the gradient in `mark.svg`.
NAVY = (20, 26, 66)

#: (filename, width, height). The platform's own stated spec, not a shared approximation: handing a
#: platform the size it asks for is what stops it re-encoding, and a re-encode on a gradient is
#: where banding comes from.
CARDS = [
    ("github-social-preview.png", 1280, 640),
    ("linkedin.png", 1200, 627),
    ("x.png", 1200, 628),
    ("facebook.png", 1200, 630),
    ("threads.png", 1200, 630),
    ("square.png", 1080, 1080),
]

#: GitHub refuses a social preview over 1 MB, and every other surface here re-encodes a large image
#: rather than refusing it, so one ceiling covers the set.
MAX_BYTES = 1024 * 1024


def test_the_kit_directory_exists_and_holds_every_card():
    missing = [name for name, _w, _h in CARDS if not (SOCIAL / name).is_file()]
    assert not missing, (
        f"missing from {SOCIAL}: {missing}. Rebuild with "
        "`python tools/packaging/build_brand_assets.py`.")


@pytest.mark.parametrize(("name", "width", "height"), CARDS)
def test_the_png_header_says_the_size_the_filename_promises(name, width, height):
    """Read from the header rather than through a library, so a truncated file fails here.

    The IHDR width and height live at bytes 16 to 24 of any PNG. This needs no dependency, which
    matters: the check that runs everywhere is worth more than the one that runs where Pillow is.
    """
    raw = (SOCIAL / name).read_bytes()
    assert raw[:8] == b"\x89PNG\r\n\x1a\n", f"{name} is not a PNG"
    got = struct.unpack(">II", raw[16:24])
    assert got == (width, height), f"{name} is {got[0]}x{got[1]}, and the spec for it is {width}x{height}"


@pytest.mark.parametrize(("name", "width", "height"), CARDS)
def test_a_card_is_small_enough_for_the_surface_that_takes_it(name, width, height):
    size = (SOCIAL / name).stat().st_size
    assert size <= MAX_BYTES, (
        f"{name} is {size / 1024:.0f} KB, over the {MAX_BYTES / 1024:.0f} KB ceiling. GitHub "
        f"refuses a social preview above it outright.")


@pytest.mark.parametrize(("name", "width", "height"), CARDS)
def test_a_card_carries_the_identity_rather_than_merely_existing(name, width, height):
    """The half `b02383a` says was missing last time: is there anything on it.

    Three properties, each cheap and each one the broken export would have failed. The corners are
    the kit's navy, so it is the right background. A meaningful share of the card is neither
    background nor near-background, so the mark is actually drawn. And the ink is pink through
    purple rather than any other hue, so it is THIS kit.
    """
    Image = pytest.importorskip("PIL.Image", reason="Pillow reads the pixels")
    im = Image.open(SOCIAL / name).convert("RGB")
    w, h = im.size
    px = im.load()

    for corner in ((4, 4), (w - 5, 4), (4, h - 5), (w - 5, h - 5)):
        got = px[corner]
        assert sum(abs(a - b) for a, b in zip(got, NAVY, strict=True)) < 30, (
            f"{name} corner {corner} is {got}, which is not the kit's navy {NAVY}")

    ink = 0
    pink = 0
    for y in range(0, h, 4):
        for x in range(0, w, 4):
            r, g, b = px[x, y]
            if sum(abs(a - c) for a, c in zip((r, g, b), NAVY, strict=True)) > 90:
                ink += 1
                # The kit's ink runs pink to purple: red leads, blue is never far behind, and green
                # is the one that stays low. A greyscale or a broken export fails this.
                if r > g + 25 and b > g:
                    pink += 1
    sampled = len(range(0, h, 4)) * len(range(0, w, 4))
    assert ink / sampled > 0.05, (
        f"{name} is {ink / sampled:.1%} ink: the mark is missing, or it was exported at a fraction "
        f"of the size the card asks for, which is what happened to the first kit")
    assert pink / max(1, ink) > 0.5, (
        f"{name}: only {pink / max(1, ink):.0%} of the ink is the kit's pink through purple, so "
        f"this is not the Bloom identity")


def test_the_generator_and_the_sources_it_reads_are_all_here():
    """A kit that cannot be rebuilt is a kit that drifts, which is the whole reason for the script."""
    for path in (ROOT / "tools" / "packaging" / "build_brand_assets.py",
                 ROOT / "assets" / "brand" / "mark.svg",
                 ROOT / "docs" / "public" / "social-card.png"):
        assert path.is_file(), f"{path} is missing, so the social cards cannot be regenerated"


def test_the_two_platforms_that_share_a_spec_share_a_card():
    """Facebook and Threads both want 1200x630, and Threads reads og:image.

    Asserted rather than left to chance so that a future edit to one of them is a visible decision
    rather than two cards drifting apart under names nobody compares.
    """
    assert (SOCIAL / "facebook.png").read_bytes() == (SOCIAL / "threads.png").read_bytes(), (
        "facebook.png and threads.png have the same spec and are no longer the same file. If that "
        "is deliberate, say why here; if not, rebuild.")
