#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Daniel Iwugo <ops@themalwarefiles.com>
"""Refuse to commit a result artefact that still carries its prompts or generations.

Why this exists
---------------
Every scoring bug in this project's history was invisible in the percentages and
obvious in the text, so the tool retains the text. That makes retention a safety
question rather than a storage one: the retained rows are harmful prompts and the
replies a model gave to them, and the repository has a public remote.

The `.gitignore` rules are the first line and they are not enough on their own. An
ignore rule stops an accidental `git add .`; it does nothing about a deliberate
`git add -f`, a path that does not match a pattern, or a file someone moves into a
tracked directory. This checker reads what is actually staged.

What counts as a finding
------------------------
Any staged `.json` or `.jsonl` carrying a `prompt`, `prompts`, `generation` or
`generations` key at any depth. Committed evidence is expected to be stripped of
those fields before it lands, so a finding is either an unstripped artefact or a
file that was never meant to be committed.

Usage
-----
    tools/check_prompt_artefacts.py --staged        # what a pre-commit hook runs
    tools/check_prompt_artefacts.py path [path...]  # what CI runs over the tree

Install as a local pre-commit step (the baseline hooks in .githooks/ are shared
across projects and installed from outside this repository, so this one is wired
in CI as the hard gate and locally by hand):

    git config core.hooksPath .githooks   # already set by the baseline install
    # then add to your local pre-commit, or run it in a pre-push:
    python3 tools/check_prompt_artefacts.py --staged || exit 1
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

#: Banned by NAME, whatever is underneath. That bluntness is the point and it has been tested:
#: on 2026-09-10 this refused ten `drift-*.json` artefacts whose `prompts` field held a FILENAME
#: rather than any prompt text, which was a false positive on the content and a true one on the
#: shape. The resolution was to rename the field in the data (`prompts_file`), not to teach this
#: check to inspect values. A gate that reasons about what a field contains is a gate with a hole
#: in it, and this one guards a public remote.
#:
#: WIDENED 2026-09-12, after a review pass measured this set catching 4 of 18 shapes it was
#: believed to cover. Every name below was checked against the whole tracked tree before being
#: added: each of these trips zero existing files, so the widening cannot be a false positive on
#: anything committed today.
#:
#: `text` IS BANNED AS OF DECISION Q-33 (2026-09-12), and it is the most valuable name here:
#: it is the likeliest field a dumped prompt lands under. It could not be banned before because
#: 12 of our own compass and head-to-head artefacts used it for single decoded TOKENS ('H',
#: ' Ben'). Those were renamed to `token_text` in the same commit, values proven unchanged,
#: following the 2026-09-10 precedent that a shape collision is fixed by renaming the field in
#: the data rather than by teaching this check to inspect values.
#:
#: `content` remains absent: one tracked file uses it, `src/senbonzakura/vendor/pins.json`,
#: where it holds a hash. Worth revisiting, and not urgent, since nothing writes prose there.
BANNED_KEYS = frozenset({
    "prompt", "prompts", "generation", "generations", "text",
    "completion", "completions", "response", "responses", "output", "outputs",
    "texts", "messages", "input", "inputs", "instruction", "question", "answer", "request",
})

#: Files whose SCHEMA is somebody else's, where a banned name is an external interface rather
#: than our choice. `dataset_info.json` is written by HuggingFace `datasets`, and its
#: `features.text` names the corpus COLUMN: renaming it would mean changing the track format
#: and repacking, and the file holds a schema rather than rows. This is the same carve-out the
#: baseline hook already makes for `behavior` and `color`, which are other people's spellings.
#:
#: Scoped to the FILENAME, deliberately. A directory-wide exemption would hide a real dump
#: dropped alongside one of these; a file named `dataset_info.json` holds a schema or it is
#: not the file this exemption is about.
FOREIGN_SCHEMA_FILES = frozenset({"dataset_info.json", "state.json"})

SUFFIXES = frozenset({".json", ".jsonl"})

# A line longer than this is not parsed. It is reported instead: a multi-megabyte
# single line in a result artefact is itself the thing worth looking at, and
# parsing it to find out costs memory a pre-commit hook should not spend.
MAX_LINE_BYTES = 1 << 20

# Depth cap on the recursive walk. Result artefacts are two or three deep; a
# structure deeper than this is either generated by something else or crafted.
MAX_DEPTH = 32


def inspect_value(obj, depth: int = 0):
    """Banned keys anywhere in a decoded JSON value, and what could not be vouched for.

    Returns `(keys, concerns, saw_a_dict)`.

    THE TWO HOLES THIS CLOSES, both of the same shape: the walk used to return an empty set
    for anything it could not read, and an empty set is what a clean file returns. Silence
    and safety were indistinguishable.

    `concerns` carries structure this check cannot speak about. The depth cap used to stop
    the walk and return nothing, so a document nested past it passed; it is now reported.
    And a name-based gate has nothing to say about a document containing no object at all,
    such as a bare array of prompt strings, so that is reported rather than called clean.
    """
    if depth > MAX_DEPTH:
        return set(), [f"nesting deeper than {MAX_DEPTH} levels was not inspected"], False
    found: set[str] = set()
    concerns: list[str] = []
    saw_a_dict = False
    if isinstance(obj, dict):
        saw_a_dict = True
        for key, value in obj.items():
            if isinstance(key, str) and key.lower() in BANNED_KEYS:
                found.add(key.lower())
            k, c, d = inspect_value(value, depth + 1)
            found |= k
            concerns += c
            saw_a_dict = saw_a_dict or d
    elif isinstance(obj, list):
        for item in obj:
            k, c, d = inspect_value(item, depth + 1)
            found |= k
            concerns += c
            saw_a_dict = saw_a_dict or d
    return found, concerns, saw_a_dict


def banned_keys_in(obj, depth: int = 0) -> set[str]:
    """Every banned key appearing anywhere in a decoded JSON value."""
    return inspect_value(obj, depth)[0]


def findings_for(obj, where: str) -> list[str]:
    """Everything worth refusing about one decoded document, as human-readable lines."""
    keys, concerns, saw_a_dict = inspect_value(obj)
    out = []
    if keys:
        out.append(f"{where}: carries {', '.join(sorted(keys))}")
    if not saw_a_dict:
        out.append(f"{where}: holds no JSON object, so a check that judges FIELD NAMES has "
                   f"nothing to read. A bare array of strings is the shape a dumped prompt "
                   f"list takes, and this check cannot clear it.")
    out += [f"{where}: {c}" for c in dict.fromkeys(concerns)]
    return out


def scan_file(path: Path) -> list[str]:
    """Findings for one file on disk, as human-readable lines. Empty means clean."""
    try:
        raw = path.read_bytes()
    except OSError as e:
        return [f"{path}: could not be read ({e}), so it cannot be cleared"]
    return scan_bytes(path, raw)


def _foreign_schema(path: Path) -> bool:
    """Is this a file whose field names belong to another tool's format?"""
    return path.name in FOREIGN_SCHEMA_FILES


def scan_bytes(path: Path, raw: bytes) -> list[str]:
    """Findings for one artefact's CONTENT, whatever it was read from.

    Separate from `scan_file` because what a pre-commit check must read is the staged
    blob rather than the working copy, and those two are not the same bytes.
    """
    findings: list[str] = []
    if _foreign_schema(path):
        return findings
    if path.suffix == ".jsonl":
        for lineno, line in enumerate(raw.split(b"\n"), 1):
            if not line.strip():
                continue
            if len(line) > MAX_LINE_BYTES:
                findings.append(f"{path}:{lineno}: line is {len(line)} bytes, too large to check")
                continue
            try:
                obj = json.loads(line)
            except (UnicodeDecodeError, json.JSONDecodeError) as e:
                findings.append(f"{path}:{lineno}: is not valid JSON ({e}), so it cannot be cleared")
                continue
            findings += findings_for(obj, f"{path}:{lineno}")
    else:
        try:
            obj = json.loads(raw)
        except (UnicodeDecodeError, json.JSONDecodeError) as e:
            # A malformed .json is reported rather than skipped: "unparseable" is
            # not "harmless", and every other .json in the tree parses.
            return [f"{path}: is not valid JSON ({e}), so it cannot be cleared"]
        findings += findings_for(obj, str(path))
    return findings


def staged_paths() -> list[Path]:
    """Files staged for commit that this checker cares about.

    Renames count (`R`) as well as additions and modifications: a file that entered the
    tree before this check existed can be moved into a published directory without its
    content ever being looked at.
    """
    try:
        out = subprocess.run(
            ["git", "diff", "--cached", "--name-only", "--diff-filter=ACMR", "-z"],
            capture_output=True, check=True, timeout=60,
        ).stdout
    except (OSError, subprocess.SubprocessError) as e:
        print(f"could not list staged files: {e}", file=sys.stderr)
        raise SystemExit(2) from e
    names = [n for n in out.decode("utf-8", "replace").split("\0") if n]
    return [Path(n) for n in names if Path(n).suffix in SUFFIXES]


def scan_staged(path: Path) -> list[str]:
    """Findings for the STAGED content of one path.

    The distinction is the whole point of a pre-commit gate. A commit records the index,
    not the working tree, so reading the file from disk checks bytes that may never be
    committed: stage an artefact full of prompts, then overwrite the working copy with a
    stripped version, and a check that reads disk passes while the commit carries the
    prompts. The staged blob is the thing that gets published.
    """
    try:
        out = subprocess.run(
            ["git", "cat-file", "blob", f":{path.as_posix()}"],
            capture_output=True, check=True, timeout=60,
        )
    except subprocess.CalledProcessError as e:
        why = e.stderr.decode("utf-8", "replace").strip()
        return [f"{path}: staged content could not be read from the index ({why}), so it cannot be cleared"]
    except (OSError, subprocess.SubprocessError) as e:
        return [f"{path}: staged content could not be read from the index ({e}), so it cannot be cleared"]
    return scan_bytes(path, out.stdout)


#: Directories holding somebody else's files. This tool exists to stop OUR harmful prompts and
#: generations reaching a public remote, and a dependency tree contains neither: whatever it
#: carries, it is not ours to strip and not ours to publish. Names rather than paths, because these
#: appear at any depth.
#: Directories whose contents are somebody else's, or this machine's, rather than the operator's
#: data. Skipping them keeps the walk fast and keeps the gate from complaining about a dependency.
#:
#: `dist` and `build` are NOT here, deliberately, and were removed on 2026-09-10. They are
#: ordinary output-directory names: a user pointing `--out build/run1` at a run is doing nothing
#: unusual, and a leak gate that silently declines to read the output directory is a gate with a
#: hole in exactly the place the artefacts land. The packaging directories they were added for are
#: covered by the fact that this gate reads TRACKED files, and neither is tracked.
VENDORED = frozenset({
    "node_modules", ".venv", "venv", "site-packages", ".git", ".tox", ".mypy_cache",
    ".pytest_cache", "__pycache__", ".eggs",
})


#: Counted so a skip is visible. A gate that silently declines to read a file reports "clean" for
#: a tree it did not look at, which is the shape this whole file exists to refuse.
_SKIPPED: list[Path] = []


def _is_vendored(path: Path) -> bool:
    if any(part in VENDORED for part in path.parts):
        _SKIPPED.append(path)
        return True
    return False


def tracked_under(directory: Path) -> list[Path] | None:
    """Version-controlled JSON and JSONL under a directory, or None if git cannot say."""
    # -C, so git is asked about the repository that CONTAINS the directory. Without it
    # git answers for the current working directory, which for any target outside it
    # errors and falls back to walking, silently: the fallback then looks like a
    # deliberate choice rather than a failed question.
    try:
        out = subprocess.run(
            ["git", "-C", str(directory), "ls-files", "-z"],
            capture_output=True, check=True, timeout=60,
        ).stdout
    except (OSError, subprocess.SubprocessError):
        return None
    names = [n for n in out.decode("utf-8", "replace").split("\0") if n]
    return [directory / n for n in names if Path(n).suffix in SUFFIXES]


def collect(paths: list[str]) -> list[Path]:
    """Expand the given paths, keeping only JSON and JSONL.

    A directory expands to what git TRACKS under it, not to what the filesystem holds.
    Walking the filesystem was wrong in both directions: it descended into .venv, so a
    run over the repository root checked fifteen dependency files and exactly one of
    ours while reporting "16 files clean", and a third-party file that happened to carry
    a "prompt" key would have blocked a commit for no reason. What this tool is for is
    what gets published, and that is what git tracks.

    Outside a repository it falls back to walking, so the tool still works on a loose
    directory of results. THE FALLBACK HAD THE DEFECT THE PARAGRAPH ABOVE DESCRIBES: the
    fix was applied to the git path and not to the walk, and the walk is the one that runs
    outside a checkout. Building the documentation puts a third-party `package.json`
    declaring a `prompts` dependency under `docs/`, and a source extract with no `.git`
    then failed this check on somebody else's file, which is the false refusal the
    tracked-files rule was introduced to prevent.
    """
    found: list[Path] = []
    for name in paths:
        p = Path(name)
        if p.is_dir():
            tracked = tracked_under(p)
            if tracked is None:
                found.extend(sorted(
                    q for q in p.rglob("*")
                    if q.is_file() and q.suffix in SUFFIXES and not _is_vendored(q)))
            else:
                found.extend(sorted(tracked))
        elif p.suffix in SUFFIXES:
            found.append(p)
    return found


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(
        prog="check_prompt_artefacts",
        description="Refuse JSON or JSONL carrying prompts or generations.")
    ap.add_argument("paths", nargs="*", help="files or directories to scan")
    ap.add_argument("--staged", action="store_true",
                    help="scan what is staged for commit instead of the given paths")
    a = ap.parse_args(argv)
    if a.staged == bool(a.paths):
        ap.error("give either --staged or one or more paths, not both and not neither")

    targets = staged_paths() if a.staged else collect(a.paths)
    read = scan_staged if a.staged else scan_file
    findings: list[str] = []
    for target in targets:
        findings.extend(read(target))

    if not findings:
        if not targets:
            # "0 file(s) clean" reads as a pass, and it is not one: it means nothing was
            # looked at. A directory of results that are not yet tracked expands to nothing,
            # so the most natural way to use this tool before committing is exactly the case
            # that silently checked nothing.
            print("prompt-artefact check: nothing to check. A directory expands to what git "
                  "TRACKS under it, so untracked files are skipped; name them directly to "
                  "check them before they are staged.")
            return 0
        skipped = f", {len(_SKIPPED)} skipped as vendored" if _SKIPPED else ""
        print(f"prompt-artefact check: {len(targets)} file(s) clean{skipped}")
        return 0

    print("prompt-artefact check FAILED: retained prompts or generations found.", file=sys.stderr)
    for line in findings:
        print(f"  {line}", file=sys.stderr)
    print("\nThese rows are harmful prompts and the replies a model gave to them, and this\n"
          "repository has a public remote. Strip the prompt and generation fields before\n"
          "committing evidence, or keep the raw artefact in the ignored results/ tree.",
          file=sys.stderr)
    return 1


if __name__ == "__main__":   # pragma: no cover
    sys.exit(main())
