#!/usr/bin/env python3
"""Derive a miniature of a head-to-head spec, so the rehearsal cannot drift from the performance.

WHY GENERATE IT RATHER THAN WRITE IT

A dry run is only worth anything if it exercises the same spec the real run will use. Written by
hand, the two files start identical and diverge the first time one is edited: the rehearsal then
proves something about a spec nobody is going to run. That is worse than no rehearsal, because it
reads as evidence.

So the miniature is produced from the real spec by a small set of named substitutions, and every
one of them MUST match or this refuses. A substitution that stops matching means the real spec
changed shape, which is exactly the moment the miniature would have gone stale.

WHAT CHANGES, AND WHAT DELIBERATELY DOES NOT

Changed: the run name, the output directory, the seed list (one seed), the trial count, and the
candidate depth. Those are the budget, and the point of a rehearsal is to spend a small one.

NOT changed: the job graph, the dependencies, the guards, the isolation flags, the image checks,
the torch-parity check, the corpus checks, the staging, the scoring and the report. Every one of
those is a thing that can be wrong, and every one runs here exactly as it will run tonight.

Usage:
    python tools/make_dryrun_spec.py holst/head-to-head-heretic.toml holst/dryrun.toml
"""
import argparse
import re
import sys

#: (description, pattern, replacement, expected match count). The count is asserted, so a
#: substitution that starts matching more or fewer places than it did fails loudly rather than
#: quietly rewriting something new.
SUBSTITUTIONS = [
    ("the run name",
     re.compile(r'^run = "([^"]+)"$', re.MULTILINE), 'run = "\\1-DRYRUN"', 1),
    ("the output directory, so a rehearsal never touches the real run's artefacts",
     re.compile(r"\$HOME/bench-out/h2h\b"), "$HOME/bench-out/h2h-dryrun", None),
    ("the seed list, down to one",
     re.compile(r"^for S in 42 43 44 45 46; do$", re.MULTILINE), "for S in 42; do", 2),
    # Anchored on what follows, so the prose that explains WHY the budget is 200 keeps saying 200.
    # A bare `--trials 200` also matches that comment, and rewriting it would leave the miniature
    # asserting that six is Heretic's own default.
    ("the trial count on the senbonzakura arm",
     re.compile(r"--trials 200 --patience 0\b"), "--trials 6 --patience 0", 1),
    ("the trial count on the Heretic arm",
     re.compile(r"--trials 200 --dir-prompts\b"), "--trials 6 --dir-prompts", 1),
    ("the candidate depth for the selection pass",
     re.compile(r"--top-n 6\b"), "--top-n 3", 1),
    ("the disk floor, since one seed needs a fraction of the space",
     re.compile(r'\[ "\$avail" -lt 80 \]'), '[ "$avail" -lt 20 ]', 1),
]


#: Applied on top of the others by `--on-card`. The committed spec says `machine = "rog"`, which
#: is what it means when holst drives the run from somewhere else. Driven from the card itself,
#: "rog" would send every job back out through ssh to the machine already running it: an extra
#: hop, an extra credential, and one more thing to drop overnight. "local" is the same work
#: without the round trip.
#:
#: This is a substitution rather than an edit to the spec, for the same reason as the rest: the
#: committed file stays correct for the ordinary case, and the variant cannot silently diverge
#: from it.
ON_CARD = [
    ("the machine, because holst is running on the card itself",
     re.compile(r'^machine = "rog"$', re.MULTILINE), 'machine = "local"', None),
]


def transform(text, on_card=False):
    """Apply every substitution, refusing if any of them stops matching what it was written for."""
    problems = []
    for label, pattern, replacement, expected in SUBSTITUTIONS + (ON_CARD if on_card else []):
        found = len(pattern.findall(text))
        if found == 0:
            problems.append(f"  {label}: pattern {pattern.pattern!r} matched nothing")
            continue
        if expected is not None and found != expected:
            problems.append(
                f"  {label}: pattern {pattern.pattern!r} matched {found} times, expected {expected}")
            continue
        text = pattern.sub(replacement, text)
    if problems:
        raise SystemExit(
            "make_dryrun_spec: the real spec no longer has the shape this rehearsal was written "
            "against, so the miniature would exercise something other than what will run:\n"
            + "\n".join(problems)
            + "\nFix the substitutions in tools/make_dryrun_spec.py to match the spec as it is now.")
    return text


FULL_BANNER = """# GENERATED by tools/make_dryrun_spec.py --on-card --full. Do not edit; regenerate.
#
# The real head-to-head, with one change from the committed spec: every job runs `local` because
# holst is driving it from the card rather than reaching the card over ssh. The budget, the job
# graph, the guards and the isolation are untouched.
"""

BANNER = """# GENERATED by tools/make_dryrun_spec.py. Do not edit; edit the real spec and regenerate.
#
# A miniature of the head-to-head: one seed, six trials, a separate output directory. The budget
# is small and everything else is identical, because the point of a rehearsal is to exercise the
# job graph, the guards, the isolation, the staging, the scoring and the report, not to measure
# anything. Nothing it produces is a result.
"""


def transform_on_card_only(text):
    """Only the machine change: the real budget, run from the card."""
    problems = []
    for label, pattern, replacement, _expected in ON_CARD:
        if not pattern.search(text):
            problems.append(f"  {label}: pattern {pattern.pattern!r} matched nothing")
            continue
        text = pattern.sub(replacement, text)
    if problems:
        raise SystemExit("make_dryrun_spec: " + "\n".join(problems))
    return text


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("source", help="the real spec")
    ap.add_argument("dest", help="where to write the miniature")
    ap.add_argument("--on-card", action="store_true",
                    help="also switch every job to `local`, for a holst driven from the card "
                         "itself rather than from another machine over ssh")
    ap.add_argument("--full", action="store_true",
                    help="keep the real budget; only apply --on-card. For the actual run, driven "
                         "from the card, where nothing about the budget should shrink.")
    a = ap.parse_args(argv)

    if a.full and not a.on_card:
        raise SystemExit("make_dryrun_spec: --full changes nothing on its own. It exists to pair "
                         "with --on-card, which is the one transform the real run needs.")

    with open(a.source, encoding="utf-8") as f:
        text = f.read()
    out = (FULL_BANNER if a.full else BANNER) + (
        transform_on_card_only(text) if a.full else transform(text, on_card=a.on_card))
    with open(a.dest, "w", encoding="utf-8") as f:
        f.write(out)
    print(f"make_dryrun_spec: wrote {a.dest} from {a.source}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
